name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: leafo/gh-actions-lua@v9
    - name: test
      run: |
        make test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: leafo/gh-actions-lua@v9
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: build tns
      run: |
        npm ci
        npm run build
        npm run build:hello
    - name: Archive TNS documents
      uses: actions/upload-artifact@v4
      with:
        name: tns-documents
        path: |
          rpn.tns
          hello.tns
